---
title: "about"
output: html_document
---

Diese App soll etwas Übersicht in die bisweilen schwer überblickbaren Twitter-Abstimmungskämpfe bringen. 

Aktuell bildet die App das Gezwitscher zu den folgenden Hashtags ab:
 
#### Vorlagen vom 8.Juni

**Vollgeldinitiative:**<br> #vollgeld, #vollgeldja, #vollgeldnein, #vollgeldinitative

**Referendum Geldspielgesetz:**<br> #geldspielgesetz, #gsgnein, #gsg, #neinzumgsg, #refgsg, #casinokartellgesetz

#### Weitere

**Referendum ASTG:**<br> #versicherungsspione, #versicherungsspitzel, #sozialdetektive

#### Infos zur Methodik

Die Tweets werden automatisiert über Hashtags oder Schlagworte identifiziert. Dieses Vorgehen hat Vor- und Nachteile. Einerseits können wir so sicherstellen, dass die gesammelten Tweets mit den Abstimmungen im Bezug stehen. Dieses Vorgehen erlaubt es uns zudem über die Zeit möglichst vergleichbare und auf ähnliche Weise erhobene Daten zu den vielen Abstimmungen zu sammeln. Kehrseite dieses Verfahrens ist, dass Tweets ohne Hashtag nicht erfasst werden. Ein Teil der Kommunikation zu den Abstimmungen fällt uns so durchs Netz. 

Diese App soll als 'Twitter-Seismograf' dienen und zeigen, wie aktiv zu den wichtigsten Abstimmungs-Hashtags getwittert wird, welche Accounts am aktivsten sind und wie die Twitter-Abstimmungskämpfe im Vergleich mit der bisherigen Mutter aller Twitter-Abstimmungsschlachten (#NoBillag) einzuordnen sind.

Wenn uns wichtige Hashtags oder Schlagworte entgangen sein sollten, ihr Fragen & Inputs zu den Daten oder zur Erhebung haben sollten sind wir froh um Hinweise!

#### Datendownload 




